[package]
name = "cloutd"
version = "0.7.0"
authors = []

[dependencies]
#pnetlink = { path = "../pnetlink" }
tokio = "0.1"
tokio-codec = "0.1"
tokio-current-thread = "0.1"
tokio-reactor = "0.1"
bytes = "0.4"
log = "0.4"
libc = "0.2"
mio = "0.6"
futures = "0.1"
pnet_sys = "0.21"
nom = "4.0"

[profile.release]
opt-level = "s"
debug = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
